import React from 'react';
import { Domain } from './types';

interface NavItem {
  domain: Domain;
  path: string;
  icon: React.FC<React.SVGProps<SVGSVGElement>>;
  description: string;
}

const SPAIcon: React.FC<React.SVGProps<SVGSVGElement>> = (props) => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" {...props}>
    <path strokeLinecap="round" strokeLinejoin="round" d="M9 12h3.75M9 15h3.75M9 18h3.75m3 .75H18a2.25 2.25 0 0 0 2.25-2.25V6.108c0-1.135-.845-2.098-1.976-2.192a48.424 48.424 0 0 0-1.123-.08m-5.801 0c-.065.21-.1.433-.1.664 0 .414.336.75.75.75h4.5a.75.75 0 0 0 .75-.75 2.25 2.25 0 0 0-.1-.664m-5.8 0A2.251 2.251 0 0 1 12 2.25a2.251 2.251 0 0 1 1.61.664m-6.828 3.14a2.25 2.25 0 0 1 2.25-2.25h2.25a2.25 2.25 0 0 1 2.25 2.25v.383c-.62.083-1.2.22-1.72.42V6.108c0-.69-.56-1.25-1.25-1.25H6.375c-.69 0-1.25.56-1.25 1.25v11.785c0 .69.56 1.25 1.25 1.25h2.25a2.25 2.25 0 0 1 2.25 2.25v.383c-.62.083-1.2.22-1.72.42V19.5a2.25 2.25 0 0 1-2.25-2.25H6.375a2.25 2.25 0 0 1-2.25-2.25V6.108Z" />
  </svg>
);

const DataVizIcon: React.FC<React.SVGProps<SVGSVGElement>> = (props) => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" {...props}>
    <path strokeLinecap="round" strokeLinejoin="round" d="M3 13.125C3 12.504 3.504 12 4.125 12h2.25c.621 0 1.125.504 1.125 1.125v6.75C7.5 20.496 6.996 21 6.375 21h-2.25A1.125 1.125 0 0 1 3 19.875v-6.75ZM9.75 8.625c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125v11.25c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 0 1-1.125-1.125V8.625ZM16.5 4.125c0-.621.504-1.125 1.125-1.125h2.25C20.496 3 21 3.504 21 4.125v15.75c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 0 1-1.125-1.125V4.125Z" />
  </svg>
);

const MobileIcon: React.FC<React.SVGProps<SVGSVGElement>> = (props) => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" {...props}>
    <path strokeLinecap="round" strokeLinejoin="round" d="M10.5 1.5H8.25A2.25 2.25 0 0 0 6 3.75v16.5a2.25 2.25 0 0 0 2.25 2.25h7.5A2.25 2.25 0 0 0 18 20.25V3.75a2.25 2.25 0 0 0-2.25-2.25H13.5m-3 0V3h3V1.5m-3 0h3m-3 18.75h3" />
  </svg>
);

const SEOIcon: React.FC<React.SVGProps<SVGSVGElement>> = (props) => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" {...props}>
    <path strokeLinecap="round" strokeLinejoin="round" d="m21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.607 10.607Z" />
  </svg>
);

const ImmersiveIcon: React.FC<React.SVGProps<SVGSVGElement>> = (props) => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" {...props}>
    <path strokeLinecap="round" strokeLinejoin="round" d="M21 7.5l-2.25-1.313M21 7.5v2.25m0-2.25l-2.25 1.313M3 7.5l2.25-1.313M3 7.5l2.25 1.313M3 7.5v2.25m9 3l2.25-1.313M12 12.75l-2.25-1.313M12 12.75V15m0 6.75l2.25-1.313M12 21.75V19.5m0 2.25l-2.25-1.313m0-16.875L12 2.25l2.25 1.313M12 2.25V4.5m-2.25 1.313L12 7.5l2.25-1.313M15 5.25l2.25-1.313m0 0L21 5.25m-3.375 0V3m-11.25 0L9 5.25m-3.375 0V3m-3.375 0L6 5.25m0 0L3 7.5" />
  </svg>
);

export const NAV_ITEMS: NavItem[] = [
    { 
        domain: Domain.SPA, 
        path: '/',
        icon: SPAIcon, 
        description: "A dynamic dashboard with interactive widgets and real-time updates." 
    },
    { 
        domain: Domain.DataViz, 
        path: '/analytics',
        icon: DataVizIcon, 
        description: "Interactive charts with AI-powered data analysis generated by Gemini." 
    },
    { 
        domain: Domain.Mobile, 
        path: '/mobile',
        icon: MobileIcon, 
        description: "A realistic preview of the application's responsive UI on a mobile device." 
    },
    { 
        domain: Domain.SEO, 
        path: '/blog',
        icon: SEOIcon, 
        description: "AI-powered content generation for a blog that would be pre-rendered for SEO." 
    },
    { 
        domain: Domain.Immersive, 
        path: '/configurator',
        icon: ImmersiveIcon, 
        description: "An interactive 3D product configurator with AI-generated marketing copy." 
    },
];